### ISSUE TITLE
in ubuntu getting ssl validation error on prem instance

### ISSUE THREAD

**Issue by nag432** [aws/aws-codedeploy-agent#105]
Please find the log for more details.

2017-03-23 02:33:31 DEBUG [codedeploy-agent(59759)]: Registering Plugins: ["codedeploy"].
2017-03-23 02:33:31 DEBUG [codedeploy-agent(59759)]: Loading plugin codedeploy from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin
2017-03-23 02:33:31 DEBUG [codedeploy-agent(59759)]: Registered Plugins: #<Set: {InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller}>.
2017-03-23 02:33:31 DEBUG [codedeploy-agent(59759)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Configuring deploy control client: Region = "us-east-1"
2017-03-23 02:33:31 DEBUG [codedeploy-agent(59759)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Deploy control endpoint override = nil
2017-03-23 02:33:31 INFO  [codedeploy-agent(59759)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandExecutor: Archives to retain is: 5}
2017-03-23 02:33:31 DEBUG [codedeploy-agent(59759)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Initializing Host Agent: Host Identifier = CodeDeployOnTuesDay
2017-03-23 02:33:31 DEBUG [codedeploy-agent(59759)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Validating CodeDeploy Plugin Configuration
2017-03-23 02:33:35 ERROR [codedeploy-agent(59759)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: Error during certificate verification on codedeploy endpoint https://codedeploy-commands.us-east-1.amazonaws.com
2017-03-23 02:33:35 DEBUG [codedeploy-agent(59759)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: certificate verify failed>
2017-03-23 02:33:35 ERROR [codedeploy-agent(59759)]: Error validating the SSL configuration: Invalid server certificate
2017-03-23 02:33:35 ERROR [codedeploy-agent(59759)]: booting child: error during start or run: SystemExit - Stopping CodeDeploy agent due to SSL validation error. - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:53:in `abort'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:53:in `validate'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:11:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2017-03-23 02:33:35 ERROR [codedeploy-agent(59759)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `exit'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `rescue in with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2017-03-23 02:33:35 INFO  [codedeploy-agent(59732)]: master 59732: Received CHLD - cleaning dead child process
2017-03-23 02:33:35 INFO  [codedeploy-agent(59732)]: master 59732: been told to replace child 59759
2017-03-23 02:33:35 INFO  [codedeploy-agent(59732)]: master 59732: not enough child processes running - missing at least 1 - respawning

**Comment by gdeblina** [comment]
The error message "Error validating the SSL configuration: Invalid server certificate" comes when we try to verify the certificate fields on instance startup but fail. The agent will only run once the certificate verification succeeds. Please verify the AWS SSL environment variables that you have set. Also make sure you are not running an old version of the agent. 
You can also set the :verbose option to true as mentioned in http://docs.aws.amazon.com/codedeploy/latest/userguide/host-cleanup.html#host-agent-config to turn on verbose logging which would help debug the issue better.

**Comment by minkruben** [comment]
I'm getting  booting child: error during start or run: Errno::ECONNRESET - Connection reset by peer - /usr/local/lib/ruby/2.0.0/net/protocol.rb:153:in `read_nonblock'

any idea ?

**Comment by asaf-erlich** [comment]
Can you tell us the agent version you're running? You can do that by running `cat /opt/codedeploy-agent/.version`?

Also, what OS are you using?

**Comment by rohkat-aws** [comment]
Have not got a response for a year hence closing it.

**Comment by DirkLachowski** [comment]
Being hit by the same error. Upgrading agent to latest ( `sudo /opt/codedeploy-agent/bin/install auto` ) fixed it.

**Comment by juanjbrown** [comment]
FYI this is still happening on the agent version `1.2.1-1868`

```
ERROR [codedeploy-agent(***)]: booting child: error during start or run: SystemExit - Stopping CodeDeploy agent due to SSL validation error.  ...
```
