### ISSUE TITLE
Scripts fail to run as non-root user

### ISSUE THREAD

**Issue by vlebo** [aws/aws-codedeploy-agent#111]
Having issues on Ubuntu 16.04 while running ApplicationStart script as non-root user in us-east-2 region

Here is my appspec file:
```
os: linux
files:
  - source: /
    destination: /opt/nd/apps/nd-platform/
    owner: nd-deploy
permissions:
  - object: /opt/nd
    pattern: "**"
    owner: nd-deploy
    group: nd-deploy
    mode: 755

hooks:

  ApplicationStop:
    - location: bin/application-stop.sh
      timeout: 300
    - location: bin/wait_for_bootstrap.sh
      runas: root

  ApplicationStart:
    - location: bin/application-start.sh
      timeout: 600
      runas: nd-deploy
```

Errror from the AWS console:

> ScriptFailed
Script Namebin/application-start.sh
MessageScript at specified location: bin/application-start.sh run as user nd-deploy failed with exit code 126
Log TailLifecycleEvent - ApplicationStart
Script - bin/application-start.sh
[stderr]/bin/bash: /opt/codedeploy-agent/deployment-root/abef4fc8-8f7b-4974-af74-2d71a7f68342/d-6PWC3F03L/deployment-archive/bin/application-start.sh: Permission denied

Error from codedeploy-agent log
```
2017-05-21 07:57:36 ERROR [codedeploy-agent(16392)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: InstanceAgent::Plugins::CodeDeployPlugin::ScriptError - Script at specified location: bin/application-start.sh run as user nd-deploy failed with exit code 126 - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:158:in `execute_script'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:115:in `block (2 levels) in execute'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:103:in `each'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:103:in `block in execute'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:173:in `create_script_log_file_if_needed'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:101:in `execute'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:142:in `block (3 levels) in map'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:130:in `each'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:130:in `block (2 levels) in map'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:62:in `execute_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:132:in `process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:65:in `perform'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:28:in `run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:38:in `block in run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:37:in `run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:70:in `block in run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:69:in `run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:33:in `block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:22:in `loop'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:22:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `block in spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in `times'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in `spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:134:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:37:in `block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `start'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:41:in `block (2 levels) in <main>'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/command_support.rb:130:in `execute'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:262:in `block in call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:275:in `call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:69:in `run'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:88:in `<main>'
2017-05-21 07:57:46 INFO  [codedeploy-agent(16392)]: Version file found in /opt/codedeploy-agent/.version. 
```

Shouldn't it run from `destination` path rather then `/opt/codedeploy-agent/...` ?

**Comment by asaf-erlich** [comment]
Can you check and include the deployment script logs? They can be found inside /opt/codedeploy-agent/deployment-root/abef4fc8-8f7b-4974-af74-2d71a7f68342/d-6PWC3F03L/logs/ ?

**Comment by vlebo** [comment]
i wrote it up in qoutes ... error from AWS console but here is from within the file too..

```
2017-05-21 07:54:41 LifecycleEvent - ApplicationStop
2017-05-21 07:54:41 Script - bin/application-stop.sh
2017-05-21 07:54:42 [stdout]Stopping application
2017-05-21 07:57:35 LifecycleEvent - ApplicationStart
2017-05-21 07:57:35 Script - bin/application-start.sh
2017-05-21 07:57:36 [stderr]/bin/bash: /opt/codedeploy-agent/deployment-root/abef4fc8-8f7b-4974-af74-2d71a7f68342/d-6PWC3F03L/deployment-archive/bin/application-start.sh: Permission denied
```

**Comment by vlebo** [comment]
permissions for scripts look fine
`/opt/codedeploy-agent/deployment-root/abef4fc8-8f7b-4974-af74-2d71a7f68342/d-6PWC3F03L/deployment-archive/bin$ ll`
```
-rwxr-x--x  1 root root  172 May 21 07:54 application-start.sh*
-rwxr-x--x  1 root root  168 May 21 07:54 application-stop.sh*
```

**Comment by asaf-erlich** [comment]
That is very odd, this is going to take some investigation on our part.

**Comment by asaf-erlich** [comment]
So let me try and understand something. Why is it that the application stop script is run fine? They both have the same permissions (application stop and application start). May I ask what's the shebang line of the application-start.sh file (and for comparison the shebang of the application-stop.sh)? Just a hunch that sometimes permission denied is not about the file but about the shebang line's executor file. It would definitely be weird either way.

**Comment by asaf-erlich** [comment]
Oh nevermind, I just looked in your appspec. ApplicationStop is run as user root while ApplicationStart is run as nd-deploy user. Ok then it definitely makes sense it's a permission problem that has to do with 711 permissions on 16 versus 771 on 14.

**Comment by asaf-erlich** [comment]
Line of code where we mark a file to be executable: https://github.com/aws/aws-codedeploy-agent/blob/9f6372357097762aa7d7c26164d7d9b1b48c4bef/lib/instance_agent/plugins/codedeploy/hook_executor.rb#L113

**Comment by asaf-erlich** [comment]
Well even on ubuntu 14 if I just try to do from irb execute FileUtils.chmod +x the file is showing up as 711 permission:
```
ubuntu@ip-172-31-8-1:/tmp$ sudo touch ruby_test_file
ubuntu@ip-172-31-8-1:/tmp$ sudo irb
irb(main):001:0> require 'fileutils'
=> true
irb(main):002:0> FileUtils.chmod("+x", '/tmp/ruby_test_file')
=> ["/tmp/ruby_test_file"]
ubuntu@ip-172-31-8-1:/tmp$ ll ruby_test_file 
-rwxr-xr-x 1 root root 0 Jul  7 22:42 ruby_test_file*
```

**Comment by asaf-erlich** [comment]
So maybe something else we do causes the file to be permission 771. Let me keep looking.

**Comment by asaf-erlich** [comment]
Alright so I see now you're setting the mode to be 755... let me see how we implement that.

**Comment by vlebo** [comment]
Sorry i was on vacation and offline :)
Please tell me if you need any more info or debugging on my side

**Comment by edward2a** [comment]
@asaf-erlich maybe I'm late to this party but would it be reasonable to just set a absolute std perms as 0755?
```FileUtils.chmod(0755, script_absolute_path(script))```

**Comment by cvrnrs** [comment]
any update on this issue im facing the same issue and im unable to launch teh application

**Comment by edward2a** [comment]
@cvrnrs may I suggest, as a workaround, copying the start/stop scripts to the instance, setting the permissions of these in the permissions section and then calling them on respective locations?

**Comment by vlebo** [comment]
Yes that could be a workaround but .... still needs investigating/fixing imho

**Comment by vlebo** [comment]
Hi all, i tried @edward2a  workaround but it's not working. Icopied scripts to `/opt/my-deploy/services/scripts/`  but It is trying to execute scripts in 

`Script does not exist at specified location: /opt/codedeploy-agent/deployment-root/56af4eec-6d33-4927-aa31-f7e8a6ce99c4/d-TOVWSSNLO/deployment-archive/opt/my-deploy/services/scripts/application_stop.sh`

**Comment by edward2a** [comment]
Hi @vlebo , just to be sure, on the location section you are specifying as follows:
  - location: /opt/my-deploy/services/scripts/application_stop.sh
and not:
  - location: opt/my-deploy/services/scripts/application_stop.sh

**Comment by vlebo** [comment]
@edward2a  correct here is diff

`@@ -15,12 +15,12 @@ hooks:
    ApplicationStop:
 -    - location: scripts/application_stop.sh
 +    - location: /opt/my-deploy/services/scripts/application_stop.sh`

**Comment by edward2a** [comment]
@vlebo ah well sorry to hear that mate, seems to work it around you'll need to even add another script (sigh) in the lines of:
```
#!/usr/bin/env bash
exec <your_actual_script_in_the_box>
```

Separate bit, dunno if it applies but I'd just have a look to confirm.
I haven't digged down the code to find out but you might want to traverse the directory path perms to make sure your _runas_ user does actually have access to execute a script inside the CD directory.
You can either ```ls -ld``` each dir on the path ```/opt/codedeploy-agent/deployment-root/56af4eec-6d33-4927-aa31-f7e8a6ce99c4/d-TOVWSSNLO/deployment-archive``` or you can (from root) ```su - <runas user>``` and try to navigate the path until the script in CD, so you make sure that user has actually access to the directory.

**Comment by edward2a** [comment]
@asaf-erlich I may be wrong but IIRC scripts (interpreted langs) require +rx to execute directly with the shebang or +r to execute via _<interpreter> <script>_.

**Comment by vlebo** [comment]
@edward2a you said:  `you might want to traverse the directory path perms to make sure your runas user does actually have access to execute a script inside the CD directory`

Those dirs are created on deploy and cannot give permissions to non-existing dir...

workaround i use is running apps with supervisord which runs app as non sudo user so start/stop script looks like ` #!/bin/bash supervisorctl start/stop appname`

I might ditch CodeDeploy in the end and write my own :/

**Comment by BuffMcBigHuge** [comment]
I've been dealing with this issue as well.

My appspec.yml as:

```
  ApplicationStart:
    - location: scripts/autostart.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/register_with_elb.sh
```

My autostart.sh:
```
NODE_ENV="$NODE_ENV" pm2 start "${PROCESSES["$proc"]}" --name "$proc" --node-args="--max_old_space_size=800" --log-date-format="MMM D/YY - HH:mm:ss"
```

pm2 has to be installed as:
```
sudo su -
npm install pm2 -g
```

...and cannot be installed as ec2-user...
```
sudo npm install pm2 -g
```

Very frustrating.

**Comment by vlebo** [comment]
Yep, any process manager will do

**Comment by asaf-erlich** [comment]
I apologize for how long it's taken to respond. Can you please provide a set of steps to reproduce the issue? A number of people have proposed suggestions but I would really like to reproduce it before attempting a fix. Thank you.

**Comment by djwinter** [comment]
I had the same _Permission denied_ symptom and eventually discovered that the `deployment-archive` directory had 700 permissions. It only happened when deploying from my local copy of the project.

The cause was my project root directory having the 700 permissions and they were being retained in the tarball deploy artefact.  `chmod go+rx the-project` has fixed it.

**Comment by JonRowe** [comment]
Ran into this today, I just get an `exit 1` in my log, no stdout, no message. Command runs fine as root in the app deploy process, command runs fine as user locally on the box.

**Comment by briananstett** [comment]
I too am experiencing issues where the `runas` directive doesn't seem to behaving as expected. I have a simple `AfterInstall` hook script that installs my ruby gems (`bundle install`). `bundle` is installed on my `amazon-growth` user but not `root`

I get the following aws codedeploy error
```
Script - scripts/bundle_install.sh
[stderr]/opt/codedeploy-agent/deployment-root/cf19337b-2377-4939-bd42-eb04df87b595/d-V8TFK8MMV/deployment-archive/scripts/bundle_install.sh: line 2: bundle: command not found
```
If I install `bundle` for root, I get the following message
```
[stdout]Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
[stdout]installing your bundle as root will break this application for all non-root
[stdout]users on this machine.
```
I think this shows that for what ever reason, my scripts are being executed as root, no matter `runas` or the `CODEDEPLOY_USER` set

appspec.yml
```
version: 0.0
os: linux
files:
  - source: /
    destination: /home/amazon-growth/rg_daemon
permissions:
  - object: "/home/amazon-growth/rg_daemon"
    owner: amazon-growth
    group: amazon-growth
    type:
      - directory

hooks:
  AfterInstall:
    - location: scripts/bundle_install.sh
      runas: amazon-growth
```

I've tried multiple combinations
1. No `runas` directive with the `CODEDEPLOY_USER` set to `amazon-growth`
2. Left `CODEDEPLOY_USER` as the default (root) with the `runas` directive set to `amazon-growth`

Any insight would be greatly appreciated.

**Comment by charusat09** [comment]
very frustrating. No solution so far. I am upgrading ruby to 2.6.3 which is available to ec2-user but not to root user. I have provided runas: ec2-user though scripts are running as root user.

**Comment by hgenchev99** [comment]
https://aws.amazon.com/premiumsupport/knowledge-center/codedeploy-agent-non-root-profile/

**Comment by rupeshk** [comment]
We ran into this issue as well. Any timeline on when this will be fixed?

**Comment by wmakley** [comment]
Just ran into this as well. RVM fails to install via CodeDeploy.

**Comment by d02540315** [comment]
> Frustrating here too. I have been dealing with this issue for days and still look for a solution. In my situation, codedeploy agent was working well as root within Amazon Linux 2. I had to switch to CIS Harden Amazon Linux2 Level2, deployment-root is automatically setup to 711 which made my script with 'runas' not working.

I had add a custom "chmod 755 /opt/codedeploy-agent/deployment-root" to make sure the scripts downloaded in boundle can be executed. It works for me.

**Comment by michaelmworthington** [comment]
Taking inspiration from the previous comment about `chmod 755 /opt/codedeploy-agent/deployment-root`, the issue in my case is that the umask on my AMI is set to 0077, so the directories that are newly created for the deployment are readable only by the root user. I was able to work around the issue by adding a `BeforeInstall` script to do a recursive chmod.

**Comment by mwjones-aws** [comment]
Duplicate of #191
