### ISSUE TITLE
scripts/install_dependencies.sh run as user root failed with exit code 127

### ISSUE THREAD

**Issue by ishandutta2007** [aws/aws-codedeploy-agent#139]
```
2017-11-05 08:28:41 ERROR [codedeploy-agent(2818)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: InstanceAgent::Plugins::CodeDeployPlugin::ScriptError - Script at specified location: scripts/install_dependencies.sh run as user root failed with exit code 127 - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:158:in 'execute_script'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:115:in 'block (2 levels) in execute
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:103:in 'each'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:103:in 'block in execute'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:173:in 'create_script_log_file_if_needed'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:101:in 'execute'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:142:in 'block (3 levels) in map'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:130:in 'each'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:130:in 'block (2 levels) in map'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:62:in 'execute_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:132:in 'process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:65:in 'perform'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:28:in 'run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:38:in 'block in run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in 'with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:37:in 'run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:70:in 'block in run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in 'with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:69:in 'run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:33:in 'block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:22:in 'loop'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:22:in 'start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in 'block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in 'fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in 'spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in 'block in spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in 'times'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in 'spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:134:in 'start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:37:in 'block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in 'fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in 'start'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:41:in 'block (2 levels) in <main>'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/command_support.rb:130:in 'call'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/command_support.rb:130:in 'execute'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:262:in 'block in call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:275:in 'call'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:275:in 'call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:69:in 'run'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:88:in '<main>'
2017-11-05 08:28:51 INFO  [codedeploy-agent(2818)]: Version file found in /opt/codedeploy-agent/.version.
2017-11-05 08:29:51 INFO  [codedeploy-agent(2818)]: [Aws::CodeDeployCommand::Client 200 60.056539 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:700595817453:instance/i-032696c71ddbbe093")  
```

appspec.yml :
```
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/
permissions:
  - object: /var/www/
    owner: root
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/post_install.sh
      timeout: 30
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300

```
Directory structure:
```

ant-media-server-bundle
|
|___ ant-media-server/
|___ appspec.yml
|___ scripts/
```

**Comment by kundankmd** [comment]
Are the files in `scripts` owned by root as well?

**Comment by ishandutta2007** [comment]
```
[ec2-user@ip-172-31-22-247 scripts]$ pwd
/opt/codedeploy-agent/deployment-root/e91392fd-8389-456c-b959-74e433620cd8/d-Q0O6X4LHP/deployment-archive/scripts

[ec2-user@ip-172-31-22-247 scripts]$ ls -ltr
total 12
-rwxr-xr-x 1 root root 141 Nov  5 08:28 start.sh
-rw-r--r-- 1 root root 704 Nov  5 08:28 post_install.sh
-rwxr-xr-x 1 root root 396 Nov  5 08:28 install_dependencies.sh
```

It shows root. Am I in the correct directory or I need to go to some other directory?
`/var/www/` didn't get created.

**Comment by cybrox** [comment]
Leaving this here as a pointer for anyone else is running into this.

The content of the AWS CodeDeploy example app `install_dependencies` is:
```
#!/bin/bash
yum install -y httpd
```

Thus everyone using an AMI with a different package manager (eg. Debian and its derivates) will run into the error described in this issue. There might be other causes for this but I think this is something the docs should make clear.

**Comment by asaf-erlich** [comment]
I went ahead and created a backlog item to fix the sample app bundle for linux (correct me if that's not the right place) to either support other OS's or document it and create another one for the other OS's. This isn't really a problem with the CodeDeploy agent though so I'm going to go ahead and close this issue. Feel free to reopen if you feel it was closed improperly.

**Comment by coffeebeantraining** [comment]
And to resurrect - this bug still exists.

**Comment by Charan-Samsani** [comment]
![image](https://github.com/aws/aws-codedeploy-agent/assets/89248547/35ccdec5-be10-497f-befb-32aca66cfe97)
can anyone help me ...
I have given the paths to the scripts and the scripts are existing in the codedeploy-agent dir, I mean they are successfully download and I even given the owner as root and made them run as root in appspec.yml too.
Still I'm getting this error

**Comment by 42510SR** [comment]
<img width="1442" alt="image" src="https://github.com/user-attachments/assets/e218a2ff-3b5b-4fde-a1d1-7f17d67c7d67">

**Comment by CharanSamsani** [comment]
> <img alt="image" width="1442" src="https://private-user-images.githubusercontent.com/86355776/352442382-e218a2ff-3b5b-4fde-a1d1-7f17d67c7d67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5OTA3NTQsIm5iZiI6MTcyMTk5MDQ1NCwicGF0aCI6Ii84NjM1NTc3Ni8zNTI0NDIzODItZTIxOGEyZmYtM2I1Yi00ZmRlLWExZDEtN2YxN2Q2N2M3ZDY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDEwNDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmODI5ZWM5NjQ2MGU4NjE2MzRkYjg1MjVkMWFmYjliZTVjNTgxZjAzMDQzNjQ0MjI3YjY4N2E4ZjVlYjNmYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kedYsqf20mr-hsJSODPBQOZJy90nkF8gH1SYFMplNIo">

Dude I really don't what is that error is even about but I remember solving it. that project is in my Github profile. I wrote wiki pages about that project you can check them If you have time.https://github.com/CharanSamsani/aws_pipeline.Refer the wiki pages you might find some answers.
