### ISSUE TITLE
Uninitialized constant when trying to use permissions in appspec.yml

### ISSUE THREAD

**Issue by mattsoftware** [aws/aws-codedeploy-agent#146]
We are using the latest codebuild agent (1.0-1.1352) as per the installation instructions. Without adding the permissions section the build works fine, after adding them the following error is displayed...

```
Starting to execute deployment from within folder /opt/codedeploy-agent/deployment-root/default-local-deployment-group/d-4AW1C7IRQ-local
See the deployment log at /opt/codedeploy-agent/deployment-root/default-local-deployment-group/d-4AW1C7IRQ-local/logs/scripts.log for more details
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:92:in `block in parse_permissions': uninitialized constant InstanceAgent::Plugins::CodeDeployPlugin::ApplicationSpecification::LinuxPermissionInfo (NameError)
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:87:in `each'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:87:in `parse_permissions'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:21:in `initialize'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:25:in `new'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:25:in `parse'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:220:in `parse_app_spec'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:100:in `initialize'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:147:in `new'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:147:in `block (3 levels) in map'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:146:in `each'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:146:in `block (2 levels) in map'
	from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:68:in `execute_command'
	from /opt/codedeploy-agent/lib/aws/codedeploy/local/deployer.rb:85:in `block in execute_events'
	from /opt/codedeploy-agent/lib/aws/codedeploy/local/deployer.rb:84:in `each'
	from /opt/codedeploy-agent/lib/aws/codedeploy/local/deployer.rb:84:in `execute_events'
	from /opt/codedeploy-agent/bin/codedeploy-local:117:in `<main>'
```

**Comment by cristianjuve** [comment]
Is this same error as https://dev.classmethod.jp/cloud/aws/codedeploy-local-test/ ?
Did this post answer your question?
I have more ore less the same issue

**Comment by rohkat-aws** [comment]
@mattsoftware were you able to solve this ?

**Comment by mattsoftware** [comment]
@rohkat-aws No, from memory I just moved it into the scripts section and have not tried since it is working that way. Sorry.
