### ISSUE TITLE
code deploy agent auto installed unknown version with ruby errors

### ISSUE THREAD

**Issue by markabishop** [aws/aws-codedeploy-agent#195]
Our ec instances have following code deploy agents installed:

/opt/codedeploy-agent/.version 
agent_version: OFFICIAL_1.0-1.1597_rpm

This was installed on Nov 9, specifically:

Sep 07 17:01:18 Updated: codedeploy-agent-1.0-1.1518.noarch
Nov 09 21:35:52 Updated: codedeploy-agent-1.0-1.1597.noarch

We cannot find this version as released: https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html

Since this auto install, we are unable to deploy and see the following error starting at the precise time of install:

2018-11-09 21:35:48 INFO  [codedeploy-agent(10132)]: [Aws::CodeDeployCommand::Client 200 60.854341 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:088684165182:instance/i-0404f906bd11f053c")

2018-11-09 21:35:49 INFO  [codedeploy-agent(10132)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 10128: shutting down
2018-11-09 21:35:54 INFO  [codedeploy-agent(31603)]: master 31603: Spawned child 1/1
2018-11-09 21:35:55 ERROR [codedeploy-agent(31607)]: booting child: error during start or run: NoMethodError - undefined method `underscore' for Seahorse::Util:Module - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:51:in `command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:76:in `<class:CommandExecutor>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:20:in `<module:CodeDeployPlugin>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:18:in `<module:Plugins>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:17:in `<module:InstanceAgent>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:16:in `<top (required)>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `require_relative'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:17:in `block in load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `each'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:29:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `block in spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in `times'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in `spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:134:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:37:in `block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `start'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:43:in `block (2 levels) in <main>'

**Comment by pmzara** [comment]
Could you send us more details about this problem? Agent logs.

**Comment by markabishop** [comment]
Here is a bigger snippet of agent log. It simply repeats boot error after install:

2018-11-09 21:29:41 INFO  [codedeploy-agent(10132)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.0-1.1518_rpm.
2018-11-09 21:30:41 INFO  [codedeploy-agent(10132)]: [Aws::CodeDeployCommand::Client 200 60.141093 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:XXX")

2018-11-09 21:30:42 INFO  [codedeploy-agent(10132)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.0-1.1518_rpm.
2018-11-09 21:31:43 INFO  [codedeploy-agent(10132)]: [Aws::CodeDeployCommand::Client 200 60.201607 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:XXX")

2018-11-09 21:31:44 INFO  [codedeploy-agent(10132)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.0-1.1518_rpm.
2018-11-09 21:32:44 INFO  [codedeploy-agent(10132)]: [Aws::CodeDeployCommand::Client 200 60.235899 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:XXX")

2018-11-09 21:32:45 INFO  [codedeploy-agent(10132)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.0-1.1518_rpm.
2018-11-09 21:33:45 INFO  [codedeploy-agent(10132)]: [Aws::CodeDeployCommand::Client 200 60.116299 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:XXX")

2018-11-09 21:33:46 INFO  [codedeploy-agent(10132)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.0-1.1518_rpm.
2018-11-09 21:34:46 INFO  [codedeploy-agent(10132)]: [Aws::CodeDeployCommand::Client 200 60.260088 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:XXX")

2018-11-09 21:34:47 INFO  [codedeploy-agent(10132)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.0-1.1518_rpm.
2018-11-09 21:34:49 INFO  [codedeploy-agent(31295)]: Checking first if any deployment lifecycle event is in progress master 10128
2018-11-09 21:34:49 INFO  [codedeploy-agent(31295)]: Stopping master 10128
2018-11-09 21:34:49 INFO  [codedeploy-agent(10128)]: master 10128: Received TERM - stopping children and shutting down
2018-11-09 21:34:49 INFO  [codedeploy-agent(10132)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 10128: Received TERM - setting internal shutting down flag and possibly finishing last run
2018-11-09 21:34:49 INFO  [codedeploy-agent(10132)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Gracefully shutting down agent child threads now, will wait up to 7200 seconds
2018-11-09 21:34:49 INFO  [codedeploy-agent(10132)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: All agent child threads have been shut down
2018-11-09 21:34:49 INFO  [codedeploy-agent(10132)]: agent exiting now
2018-11-09 21:35:48 INFO  [codedeploy-agent(10132)]: [Aws::CodeDeployCommand::Client 200 60.854341 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-west-2:XXX")

2018-11-09 21:35:49 INFO  [codedeploy-agent(10132)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller of master 10128: shutting down
2018-11-09 21:35:54 INFO  [codedeploy-agent(31603)]: master 31603: Spawned child 1/1
2018-11-09 21:35:55 ERROR [codedeploy-agent(31607)]: booting child: error during start or run: NoMethodError - undefined method `underscore' for Seahorse::Util:Module - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:51:in `command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:76:in `<class:CommandExecutor>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:20:in `<module:CodeDeployPlugin>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:18:in `<module:Plugins>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:17:in `<module:InstanceAgent>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:16:in `<top (required)>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `require_relative'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:17:in `block in load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `each'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:29:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `block in spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in `times'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:195:in `spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:134:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:37:in `block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `start'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:43:in `block (2 levels) in <main>'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/command_support.rb:126:in `execute'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/app_support.rb:284:in `block in call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/app_support.rb:297:in `call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.11.0/lib/gli/app_support.rb:79:in `run'
/opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:90:in `<main>'
2018-11-09 21:35:55 INFO  [codedeploy-agent(31603)]: master 31603: Received CHLD - cleaning dead child process
2018-11-09 21:35:55 INFO  [codedeploy-agent(31603)]: master 31603: been told to replace child 31607
2018-11-09 21:35:55 INFO  [codedeploy-agent(31603)]: master 31603: not enough child processes running - missing at least 1 - respawning
2018-11-09 21:35:55 INFO  [codedeploy-agent(31603)]: Started master 31603 with 1 children
2018-11-09 21:36:00 INFO  [codedeploy-agent(31603)]: master 31603: Spawned child 1/1
2018-11-09 21:36:00 ERROR [codedeploy-agent(31616)]: booting child: error during start or run: NoMethodError - undefined method `underscore' for Seahorse::Util:Module - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:51:in `command'
'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:76:in `<class:CommandExecutor>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:20:in `<module:CodeDeployPlugin>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:18:in `<module:Plugins>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:17:in `<module:InstanceAgent>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:16:in `<top (required)>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `require_relative'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:17:in `block in load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `each'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:29:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2018-11-09 21:36:01 INFO  [codedeploy-agent(31603)]: master 31603: Received CHLD - cleaning dead child process
2018-11-09 21:36:01 INFO  [codedeploy-agent(31603)]: master 31603: been told to replace child 31616
2018-11-09 21:36:01 INFO  [codedeploy-agent(31603)]: master 31603: not enough child processes running - missing at least 1 - respawning
2018-11-09 21:36:06 INFO  [codedeploy-agent(31603)]: master 31603: Spawned child 1/1
2018-11-09 21:36:07 ERROR [codedeploy-agent(31739)]: booting child: error during start or run: NoMethodError - undefined method `underscore' for Seahorse::Util:Module - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:51:in `command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:76:in `<class:CommandExecutor>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:20:in `<module:CodeDeployPlugin>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:18:in `<module:Plugins>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:17:in `<module:InstanceAgent>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:16:in `<top (required)>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `require_relative'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:17:in `block in load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `each'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:29:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2018-11-09 21:36:07 INFO  [codedeploy-agent(31603)]: master 31603: Received CHLD - cleaning dead child process
2018-11-09 21:36:07 INFO  [codedeploy-agent(31603)]: master 31603: been told to replace child 31739
2018-11-09 21:36:07 INFO  [codedeploy-agent(31603)]: master 31603: not enough child processes running - missing at least 1 - respawning
2018-11-09 21:36:12 INFO  [codedeploy-agent(31603)]: master 31603: Spawned child 1/1
2018-11-09 21:36:13 ERROR [codedeploy-agent(31762)]: booting child: error during start or run: NoMethodError - undefined method `underscore' for Seahorse::Util:Module - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:51:in `command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:76:in `<class:CommandExecutor>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:20:in `<module:CodeDeployPlugin>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:18:in `<module:Plugins>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:17:in `<module:InstanceAgent>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:16:in `<top (required)>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `require_relative'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin.rb:2:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/usr/local/rvm/rubies/ruby-2.4.1/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:17:in `block in load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `each'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:13:in `load_plugins'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:29:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2018-11-09 21:36:13 INFO  [codedeploy-agent(31603)]: master 31603: Received CHLD - cleaning dead child process
2018-11-09 21:36:13 INFO  [codedeploy-agent(31603)]: master 31603: been told to replace child 31762
2018-11-09 21:36:13 INFO  [codedeploy-agent(31603)]: master 31603: not enough child processes running - missing at least 1 - respawning
2018-11-09 21:36:18 INFO  [codedeploy-agent(31603)]: master 31603: Spawned child 1/1
2018-11-09 21:36:18 ERROR [codedeploy-agent(31768)]: booting child: error during start or run: NoMethodError - undefined method `underscore' for Seahorse::Util:Module - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:51:in `command'

**Comment by markabishop** [comment]
Please advise on action as this is impacting our ability to release new versions of our service. Is it possible to downgrade this version as it clearly has issues (and there is no documentation on it).

**Comment by rohkat-aws** [comment]
@markabishop If anything it might signify a problem in the update process, we have not yet heard from any client about any issue about the new version. Regarding the update process, I think this might be related to the way the aws ruby sdk is being used . Can you explain on how the ruby sdk is installed on the ec2 instance . And are the instances spun up during auto scaling or are they old instances .

**Comment by markabishop** [comment]
Instances are older. One created of logs above created: September 7, 2018 at 9:59:24 AM UTC-7

AMI has ruby installed via: 

            # Install RVM
            echo "Installing rvm and ruby-${RubyVersionNumber}"
            gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
            su centos -c 'curl -sSL https://get.rvm.io | sudo bash -s stable --ruby'
            usermod -a -G rvm -a 'centos'
            usermod -a -G rvm -a 'services'
            echo "source /etc/profile.d/rvm.sh" >> /home/services/.bashrc

            # Install Ruby
            source /etc/profile.d/rvm.sh
            rvm install "ruby-${RubyVersionNumber}"
            rvm --default use "ruby-${RubyVersionNumber}"

with Ruby version = 2.4.1

AWS SDK is used by service; here is service's Gemfile.lock

    aws-eventstream (1.0.1)
    aws-partitions (1.100.0)
    aws-sdk-core (3.24.1)
      aws-eventstream (~> 1.0)
      aws-partitions (~> 1.0)
      aws-sigv4 (~> 1.0)
      jmespath (~> 1.0)
    aws-sdk-sqs (1.4.0)
      aws-sdk-core (~> 3)
      aws-sigv4 (~> 1.0)
    aws-sigv4 (1.0.3)

We use vendor cache and our afterinstall script runs:
export PATH="/usr/local/rvm/gems/ruby-2.4.1/bin:/usr/local/rvm/rubies/ruby-2.4.1/bin:/usr/local/rvm/bin:$PATH"
RAILS_ENV=production bundle install --local --without development test

echo "running bundle install - done"

echo "running rake db:migrate"
RAILS_ENV=production bundle exec rake db:migrate
echo "running rake db:migrate - done"

echo "update crontab"
chmod +x bin/*
RAILS_ENV=production bundle exec whenever --update-crontab
echo "update crontab - done"

**Comment by rohkat-aws** [comment]
@markabishop i suspect the ruby sdk was updated recently because we right now only support aws ruby sdk 2 . Is it possible to remove it ?

**Comment by markabishop** [comment]
We have had it working for over a month with codedeploy-agent-1.0-1.1518.noarch
We need sdk 3 for sqs functionality. How can I downgrade codedeploy to previous version which worked?

**Comment by rohkat-aws** [comment]
i am sorry not right now, basically we need to restrict code deploy agent to use its own ruby sdk and not  global ruby sdk.

**Comment by markabishop** [comment]
We have found a manual work around which also explains what is happening. If we uninstall aws-sdk-core 3.x and associated gems and remove dependency from the application then we are able to proceed. 
My conjecture on what happened is:

1. codedeploy agent 1518 has been running for months when app was using sdk 2
2. codedeploy deployed application that installed sdk 3 gem several weeks ago
3. On Friday, codedeploy auto upgraded to 1597 and restarted. When it restarted it loaded sdk 3 and was unable to continue boot. 

Suspect others will run into this issue that is triggered by auto update.

**Comment by rohkat-aws** [comment]
@markabishop its a known issue and has been answered multiple times, and is not something that will be trigerred by an auto update of the agent , It will be triggered if sdk 3 is installed . Having said that its not ideal behavior and we have issues open for them to work on .
