### ISSUE TITLE
codedeploy won't work with OpenStack

### ISSUE THREAD

**Issue by benishak** [aws/aws-codedeploy-agent#200]
I'm getting this Invalid AZ because i'm using OpenStack and this command 

```
curl http://169.254.169.254/latest/meta-data/placement/availability-zone
```

is working but it not returning something like `us-east-1b` 

this is very useless, you should makes us configure the AZ like we do with the region or find a different way to identify wether the instance is an EC2 or not

**Comment by benishak** [comment]
i'm taking about this

https://github.com/aws/aws-codedeploy-agent/blob/master/lib/instance_metadata.rb
```
raise "Invalid availability zone name: #{az}" unless
      az =~ /[a-z]{2}-[a-z]+-\d+[a-z]/
    az.chop
```

**Comment by benishak** [comment]
I changed the ip to let it timeout but it is returning this now
```
2018-12-28 14:17:04 ERROR [codedeploy-agent(4776)]: booting child: error during start or run: Errno::ECONNREFUSED - Failed to open TCP connection to 127.254.169.254:80 (Connection refused - connect(2) for "127.254.169.254" port 80) - /usr/lib/ruby/2.3.0/net/http.rb:882:in `rescue in block in connect'
/usr/lib/ruby/2.3.0/net/http.rb:879:in `block in connect'
/usr/lib/ruby/2.3.0/timeout.rb:91:in `block in timeout'
/usr/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
/usr/lib/ruby/2.3.0/net/http.rb:878:in `connect'
/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/usr/lib/ruby/2.3.0/net/http.rb:852:in `start'
/usr/lib/ruby/2.3.0/net/http.rb:584:in `start'
/opt/codedeploy-agent/lib/instance_metadata.rb:51:in `http_get'
/opt/codedeploy-agent/lib/instance_metadata.rb:22:in `region'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:38:in `initialize'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `new'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:32:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2018-12-28 14:17:04 ERROR [codedeploy-agent(4776)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:90:in `exit'
```

**Comment by annamataws** [comment]
Hi,

I have a few questions so we can better understand the issue. Can you please tell me more about your setup? Is your instance an on-premise instance? What is your curl command returning? 

Thank you

**Comment by annamataws** [comment]
Hi,

Are you wanting a way to make on-premise instances not be viewed as on-premise instances by CodeDeploy?

**Comment by benishak** [comment]
it is the other way round
i want on prem instance to be viewed as an on prem instance 
but code deploy think that my instance is EC2 instance because it got response from ` http://169.254.169.254/latest/meta-data/placement/availability-zone` but it got an non-AWS AZ format.

In OpenStack you can query instance meta data just like in EC2 from http://169.254.169.254/latest/meta-data/

**Comment by annamataws** [comment]
I see. We will look into that.
