### ISSUE TITLE
Windows 2016: Error during start or run

### ISSUE THREAD

**Issue by barracksbuilder** [aws/aws-codedeploy-agent#209]
OS: Windows 2016 Server (On-Premise)
Codedeploy-agent: agent_version: OFFICIAL_1.0.1.1597_msi
Windows firewall: Off (full outgoing allowed, DNS works can view webpages in chrome)
Registered in AWS Successfully as an Instance (Using the same role as my Linux boxes)

I keep receiving the following error in the logs:
```
2019-05-01T15:12:10 INFO  [codedeploy-agent(696)]: CodeDeploy Instance Agent Service: started
2019-05-01T15:12:31 ERROR [codedeploy-agent(696)]: CodeDeploy Instance Agent Service: CodeDeploy Instance Agent Service: error during start or run: Net::OpenTimeout - execution expired - C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/net/http.rb:880:in `initialize'
C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/net/http.rb:880:in `open'
C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/net/http.rb:880:in `block in connect'
C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/timeout.rb:101:in `timeout'
C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/net/http.rb:878:in `connect'
C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/net/http.rb:852:in `start'
C:/Windows/TEMP/ocrF5F1.tmp/lib/ruby/2.3.0/net/http.rb:584:in `start'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/lib/instance_metadata.rb:51:in `http_get'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/lib/instance_metadata.rb:12:in `host_identifier'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:39:in `initialize'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `new'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:10:in `runner'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/bin/winagent.rb:42:in `block (2 levels) in service_main'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/bin/winagent.rb:41:in `synchronize'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/bin/winagent.rb:41:in `block in service_main'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/bin/winagent.rb:89:in `with_error_handling'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/bin/winagent.rb:38:in `service_main'
C:/Windows/Temp/ocrF5F1.tmp/lib/ruby/gems/2.3.0/gems/win32-service-0.8.10/lib/win32/daemon.rb:316:in `mainloop'
C:/Windows/Temp/ocrF5F1.tmp/lib/ruby/gems/2.3.0/gems/win32-service-0.8.10/lib/win32/daemon.rb:214:in `mainloop'
C:/Windows/TEMP/ocrF5F1.tmp/src/opt/codedeploy-agent/bin/winagent.rb:104:in `<main>'
```

I have the following C:\programdata\amazon\codedeploy\conf.onpremises.yml:
```
---
aws_credentials_file: C:/ProgramData/Amazon/CodeDeploy/credentials
region: us-east-1
```

The C:\programdata\amazon\codedeploy\conf.yml:
```
---
:log_dir: 'Amazon/CodeDeploy/log'
:root_dir: 'Amazon/CodeDeploy'
:verbose: true
:wait_between_runs: 1
:wait_after_error: 1
:max_revisions: 3
:region: us-east-1
```

C:\programdata\amazon\codedeploy\credentials:
```
[default]
aws_access_key_id = **REDACTED**
aws_secret_access_key = **REDACTED**
```

This very similar config is running in my Linux on-premise environments just fine. I can't figure out why it keeps throwing the OpenTimeout error.

**Comment by barracksbuilder** [comment]
User error was mmissing iam_user_arn in the conf.onpremesis.yml:

````
---
aws_access_key_id: secret-key-id
aws_secret_access_key: secret-access-key
iam_user_arn: iam-user-arn
region: supported-region
````
