### ISSUE TITLE
CodeDeploy fails with error "undefined method `each_pair'"

### ISSUE THREAD

**Issue by TheToddLuci0** [aws/aws-codedeploy-agent#247]
Error message from `/var/log/aws/codedeploy-agent/codedeploy-agent.log`
```
2020-06-10 20:12:47 ERROR [codedeploy-agent(1228)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: NoMethodError - undefined method `each_pair' for #<Array:0x00007f0843cc0310> Did you mean? each_slice - 
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:64:in `parse_hooks'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:21:in `initialize'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:27:in `new'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:27:in `parse'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:230:in `parse_app_spec'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/hook_executor.rb:101:in `initialize'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:147:in `new'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:147:in `block (3 levels) in map'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:146:in `each'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:146:in `block (2 levels) in map'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:68:in `execute_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:114:in `process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:96:in `acknowledge_and_process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:75:in `block in perform' 
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task' 
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop' 
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2020-06-10 20:12:47 WARN[codedeploy-agent(1228)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error"
2020-06-10 20:12:47 INFO[codedeploy-agent(1228)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.0-1.1597_deb.
```

Ruby version `ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]`

Codedeploy-agent version `v1.0-1.1597`

OS-Release 
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

Running on EC2 in US-East-2

**Comment by dejonghe** [comment]
Hitting this exact error as well on CentOs on lightsail.

**Comment by dejonghe** [comment]
Confirmed to happen after updating agent to v1.1.2-1855 as well as v1.0-1.1597

**Comment by dejonghe** [comment]
I ran into this, the value of your hooks map, is likely an array not a map, make sure you dont have a dash before the hook name:

```
hooks:
  BeforeInstall:
    - location: some/path.sh
      timeout: 180
```
