### ISSUE TITLE
CodeDeploy Download Bundle Error: cannot load such file -- aws-sdk-core/s3 

### ISSUE THREAD

**Issue by shruk95** [aws/aws-codedeploy-agent#266]
I updated my CodeDeploy agent to V 1.12 on Windows-2019 Recently. It was working fine and suddenly i started facing the issue with Download Bundle step.

When i check the code deploy agent logs this is what i found.

`2020-08-14T12:51:42 ERROR [codedeploy-agent(6780)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: LoadError - cannot load such file -- aws-sdk-core/s3 - C:/Windows/TEMP/ocr2D24.tmp/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
C:/Windows/TEMP/ocr2D24.tmp/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in 'require'
C:/Windows/TEMP/ocr2D24.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:242:in 'download_from_s3'
C:/Windows/TEMP/ocr2D24.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:82:in 'block in <class:CommandExecutor>'
C:/Windows/TEMP/ocr2D24.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:68:in 'execute_command'
C:/Windows/TEMP/ocr2D24.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:115:in 'process_command'
C:/Windows/TEMP/ocr2D24.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:97:in 'acknowledge_and_process_command'
C:/Windows/TEMP/ocr2D24.tmp/src/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:76:in 'block in perform'
C:/Windows/Temp/ocr2D24.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in 'run_task'
C:/Windows/Temp/ocr2D24.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in 'block (3 levels) in create_worker'
C:/Windows/Temp/ocr2D24.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in 'loop'
C:/Windows/Temp/ocr2D24.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in 'block (2 levels) in create_worker'
C:/Windows/Temp/ocr2D24.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in 'catch'
C:/Windows/Temp/ocr2D24.tmp/gemhome/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in 'block in create_worker'
C:/Windows/Temp/ocr2D24.tmp/lib/ruby/gems/2.3.0/gems/logging-2.2.2/lib/logging/diagnostic_context.rb:474:in 'block in create_with_logging_context'
2020-08-14T12:51:42 WARN  [codedeploy-agent(6780)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error" 
2020-08-14T12:51:42 INFO  [codedeploy-agent(6780)]: Version file found in C:/ProgramData/Amazon/CodeDeploy/.version with agent version OFFICIAL_1.1.2.1855_msi.
2020-08-14T12:51:42 INFO  [codedeploy-agent(6780)]: [Aws::CodeDeployCommand::Client 200 0.030993 0 retries] put_host_command_complete(command_status:"Failed",diagnostics:{format:"JSON",payload:"{\"error_code\":5,\"script_name\":\"\",\"message\":\"cannot load such file -- aws-sdk-core/s3\",\"log\":\"\"}"},host_command_identifier:"eyJiYXRjaElkIjoiOWRhODUzYzZjMWQyMDc0MmJmOGEwNGVjYzg0MDA1ODQvcHVibGljMDA0IiwiZGVwbG95bWVudElkIjoiQ29kZURlcGxveS91cy1lYXN0LTEvcHJvZC9vcnBoZXVzOnB1YmxpYzAwMC85NjA1MTUwMzM1NDI6ZC01WEw4UlE3WDUiLCJob3N0SWQiOiJhcm46YXdzOmVjMjp1cy1lYXN0LTE6OTYwNTE1MDMzNTQyOmluc3RhbmNlL2ktMGJhN2U5MWQ4MGIyYzJiYjkiLCJjb21tYW5kSWQiOiJBcG9sbG9EZXBsb3lDb250cm9sU2VydmljZXxhcm46YXdzOmVjMjp1cy1lYXN0LTE6OTYwNTE1MDMzNTQyOmluc3RhbmNlL2ktMGJhN2U5MWQ4MGIyYzJiYjl8MnwwIiwiY29tbWFuZE5hbWUiOiJEb3dubG9hZEJ1bmRsZSIsImNvbW1hbmRJbmRleCI6MiwiYXR0ZW1wdEluZGV4IjoxfQ==")  `

I was able to get it back to  working by restarting CodeDeploy Agent , but wanted to know if their is a better solution for it.

**Comment by brblck** [comment]
This looks like it's potentially a bad installation of the agent and some expected components are missing. Was the agent installation baked into an AMI on this instance? Or installed manually?

**Comment by shruk95** [comment]
I installed it manually by following the CodeDeploy installation Document.

**Comment by philstrong** [comment]
Please update to the latest version of CodeDeploy.
