### ISSUE TITLE
Agent can't connect to deploy control endpoint

### ISSUE THREAD

**Issue by dryan** [aws/aws-codedeploy-agent#268]
This is the same issue as #102 

I'm trying to use CodeDeploy in an on-premise configuration for Lightsail. While the error logs have an SSL error, the underlying issue is that the server cannot resolve `https://codedeploy-commands.us-east-1a.amazonaws.com`.

Here's the output of the agent's log:

```
2020-09-02 20:39:20 INFO  [codedeploy-agent(1786)]: Started master 1786 with 1 children
2020-09-02 20:39:24 INFO  [codedeploy-agent(1786)]: master 1786: Spawned child 1/1
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: Registering Plugins: ["codedeploy"].
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: Loading plugin codedeploy from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: Registered Plugins: #<Set: {InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller}>.
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Configuring deploy control client: Region="us-east-1a"
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Deploy control endpoint override=
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Enable auth policy = false
2020-09-02 20:39:24 INFO  [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandExecutor: Archives to retain is: 5}
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Initializing Host Agent: Host Identifier = arn:aws:iam::886797411086:user/OurWinsconsinRev.comCodeDeploy
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Validating CodeDeploy Plugin Configuration
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: Current deploy control endpoint: https://codedeploy-commands.us-east-1a.amazonaws.com
2020-09-02 20:39:24 ERROR [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: Error during certificate verification on codedeploy endpoint https://codedeploy-commands.us-east-1a.amazonaws.com
2020-09-02 20:39:24 DEBUG [codedeploy-agent(1814)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: #<SocketError: Failed to open TCP connection to codedeploy-commands.us-east-1a.amazonaws.com:443 (getaddrinfo: Name or service not known)>
2020-09-02 20:39:24 ERROR [codedeploy-agent(1814)]: Error validating the SSL configuration: Invalid server certificate
2020-09-02 20:39:24 ERROR [codedeploy-agent(1814)]: booting child: error during start or run: SystemExit - Stopping CodeDeploy agent due to SSL validation error. - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:65:in `abort'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:65:in `validate'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:11:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:32:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2020-09-02 20:39:24 ERROR [codedeploy-agent(1814)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:90:in `exit'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:90:in `rescue in with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:77:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:78:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:206:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:204:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:283:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2020-09-02 20:39:24 INFO  [codedeploy-agent(1786)]: master 1786: Received CHLD - cleaning dead child process
2020-09-02 20:39:24 INFO  [codedeploy-agent(1786)]: master 1786: been told to replace child 1814
2020-09-02 20:39:24 INFO  [codedeploy-agent(1786)]: master 1786: not enough child processes running - missing at least 1 - respawning
```

The relevant lines are 12-15.

Here's the output of a `dig` and `curl` attempt to find the endpoint.

```
❯ dig codedeploy-commands.us-east-1a.amazonaws.com 

; <<>> DiG 9.11.3-1ubuntu1.1-Ubuntu <<>> codedeploy-commands.us-east-1a.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 52384
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;codedeploy-commands.us-east-1a.amazonaws.com. IN A

;; Query time: 0 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Wed Sep 02 20:40:29 UTC 2020
;; MSG SIZE  rcvd: 73
```

```
❯ curl https://codedeploy-commands.us-east-1a.amazonaws.com
curl: (6) Could not resolve host: codedeploy-commands.us-east-1a.amazonaws.com
```

This is on Ubuntu 18.04 LTS on Lightsail in US East 1.

**Comment by dryan** [comment]
Figured out the issue here was a typo in the region in the config file.

**Comment by ashish34567** [comment]
> Figured out the issue here was a typo in the region in the config file.

what is the path of that config file?
