### ISSUE TITLE
Bypass SSL check

### ISSUE THREAD

**Issue by nwalke** [aws/aws-codedeploy-agent#28]
I would appreciate a way to bypass the SSL verification check.  We intercept all outbound traffic, including HTTPS for PCI reasons.  Even though I have a file in `/etc/profile.d` with the following contents:
```
export AWS_SSL_CA_DIRECTORY="/etc/ssl/certs"
export AWS_SSL_CA_BUNDLE="/etc/ssl/certs/squid-proxy.pem"
export SSL_CERT_FILE="/etc/ssl/certs/squid-proxy.pem"
```
On first boot, the agent still errors.  It eventually starts working after failing twice.
```
2015-09-18 10:40:03 INFO  [codedeploy-agent(4057)]: master 4057: Spawned child 1/1
2015-09-18 10:40:04 INFO  [codedeploy-agent(4061)]: On Premises config file does not exist or not readable
2015-09-18 10:40:04 INFO  [codedeploy-agent(4057)]: Started master 4057 with 1 children
2015-09-18 10:42:11 ERROR [codedeploy-agent(4061)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: Error during certificate verification on codedeploy endpoint https://codedeploy-commands.us-east-1.amazonaws.com
2015-09-18 10:42:11 ERROR [codedeploy-agent(4061)]: Error validating the SSL configuration: Invalid server certificate
2015-09-18 10:42:11 ERROR [codedeploy-agent(4061)]: booting child: error during start or run: SystemExit - Stopping CodeDeploy agent due to SSL validation error. - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:53:in `abort'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:53:in `validate'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:11:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:198:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:188:in `block in spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:187:in `times'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:187:in `spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:133:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:35:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:35:in `start'
/opt/codedeploy-agent/bin/codedeploy-agent:37:in `block (2 levels) in <main>'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/command_support.rb:130:in `call'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/command_support.rb:130:in `execute'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:262:in `block in call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:275:in `call'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:275:in `call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:69:in `run'
/opt/codedeploy-agent/bin/codedeploy-agent:84:in `<main>'
2015-09-18 10:42:11 ERROR [codedeploy-agent(4061)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `exit'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `rescue in with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:198:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:188:in `block in spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:187:in `times'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:187:in `spawn_children'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:133:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:36:in `block in start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:35:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:35:in `start'
/opt/codedeploy-agent/bin/codedeploy-agent:37:in `block (2 levels) in <main>'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/command_support.rb:130:in `call'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/command_support.rb:130:in `execute'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:262:in `block in call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:275:in `call'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:275:in `call_command'
/opt/codedeploy-agent/vendor/gems/gli-2.5.6/lib/gli/app_support.rb:69:in `run'
/opt/codedeploy-agent/bin/codedeploy-agent:84:in `<main>'
2015-09-18 10:42:11 INFO  [codedeploy-agent(4057)]: master 4057: Received CHLD - cleaning dead child process
2015-09-18 10:42:11 INFO  [codedeploy-agent(4057)]: master 4057: been told to replace child 4061
2015-09-18 10:42:11 INFO  [codedeploy-agent(4057)]: master 4057: not enough child processes running - missing at least 1 - respawning
2015-09-18 10:42:16 INFO  [codedeploy-agent(4057)]: master 4057: Spawned child 1/1
2015-09-18 10:42:16 INFO  [codedeploy-agent(4910)]: On Premises config file does not exist or not readable
2015-09-18 10:44:23 ERROR [codedeploy-agent(4910)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: Error during certificate verification on codedeploy endpoint https://codedeploy-commands.us-east-1.amazonaws.com
2015-09-18 10:44:23 ERROR [codedeploy-agent(4910)]: Error validating the SSL configuration: Invalid server certificate
2015-09-18 10:44:23 ERROR [codedeploy-agent(4910)]: booting child: error during start or run: SystemExit - Stopping CodeDeploy agent due to SSL validation error. - /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:53:in `abort'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:53:in `validate'
/opt/codedeploy-agent/lib/instance_agent/agent/base.rb:11:in `runner'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:31:in `block in prepare_run'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:198:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:275:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `call'
/opt/codedeploy-agent/vendor/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2015-09-18 10:44:23 ERROR [codedeploy-agent(4910)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `exit'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:67:in `rescue in with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:30:in `prepare_run'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:64:in `block in prepare_run_with_error_handling'
/opt/codedeploy-agent/lib/instance_agent/runner/child.rb:55:in `with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:63:in `prepare_run_with_error_handling'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/child.rb:20:in `start'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:198:in `block in spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `fork'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:196:in `spawn_child'
/opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb:275:in `block (2 levels) in replace_terminated_children'
/opt/codedeploy-agent/vendor/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `call'
/opt/codedeploy-agent/vendor/gems/logging-1.8.1/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2015-09-18 10:44:23 INFO  [codedeploy-agent(4057)]: master 4057: Received CHLD - cleaning dead child process
2015-09-18 10:44:23 INFO  [codedeploy-agent(4057)]: master 4057: been told to replace child 4910
2015-09-18 10:44:23 INFO  [codedeploy-agent(4057)]: master 4057: not enough child processes running - missing at least 1 - respawning
2015-09-18 10:44:28 INFO  [codedeploy-agent(4057)]: master 4057: Spawned child 1/1
2015-09-18 10:44:28 INFO  [codedeploy-agent(4920)]: On Premises config file does not exist or not readable
2015-09-18 10:46:00 INFO  [codedeploy-agent(4920)]: [Aws::CodeDeployCommand::Client 200 60.940396 0 retries] poll_host_command(host_identifier:"arn:aws:ec2:us-east-1:999999999999:instance/i-bbbbbbbb")
```

Is there a way to fix this or bypass the SSL check completely?

**Comment by nwalke** [comment]
Because the `AWS_SSL_CA` features are undocumented, AWS support is completely unable to help me fix this issue.  The only way I can see to get this fixed is by talking to the developers here.  

Am I doing something wrong in the way that I added the `AWS_SSL_CA` variables?  I see the release notes say that the agent now sources /etc/profile, I would assume that it would pick up the variables I added.

**Comment by suryanarayanan** [comment]
Hi,
The error message "Error validating the SSL configuration: Invalid server certificate" seems to be coming from the place where we verify the certificate fields. https://github.com/aws/aws-codedeploy-agent/blob/master/lib/instance_agent/plugins/codedeploy/codedeploy_control.rb#L48

Your AWS SSL environment variables look right to me and I would recommend against disabling the SSL peer verify check. If your instance is behind a proxy you might want to export HTTP_PROXY with the proxy url in /etc/profile.
Thanks.

**Comment by nwalke** [comment]
We don't use Squid as an HTTP proxy.  We use it on our nat instances to monitor all traffic.  Until such time that I can create a codedeploy VPC endpoint, this is how I have to do it.

I just wanted to point out that...  
A.  It would be nice to have the option to disable them.
B.  They don't work now, because eventually the agent just starts running anyways.

**Comment by suryanarayanan** [comment]
Thanks for your feedback. I'm not sure what causes the failures in checking the cert fields in the first two attempts. But the agent doesn't run unless https://github.com/aws/aws-codedeploy-agent/blob/master/lib/instance_agent/plugins/codedeploy/codedeploy_control.rb#L93 succeeds.

Can you turn on the debug log by setting *:verbose* to true in the agent config and restart the agent? If you can paste the debug logs we might be able to see more information on what causes the failure.

**Comment by nwalke** [comment]
@suryanarayanan Thanks for continuing to look in to this for me.  

For reference, here's my agent log with our nat/proxy/squid box's cert included with `AWS_SSL_CA_DIRECTORY` and `AWS_SSL_CA_BUNDLE`: https://gist.github.com/nwalke/65b4663fdfbf8edeb875

With `verbose` set to `true`: https://gist.github.com/nwalke/d6e21c2ddb7e177e6133

On my second start up of the codedeploy-agent, it doesn't error at all.  

A little info about how we get a box to this point..   We create a base AMI that has the file under /etc/profile.d/codedeployssl.sh that sets the following:
```
export AWS_SSL_CA_DIRECTORY="/etc/ssl/certs"
export AWS_SSL_CA_BUNDLE="/etc/ssl/certs/squid-proxy.pem"
export SSL_CERT_FILE="/etc/ssl/certs/squid-proxy.pem"
```

That base AMI includes setting up some dependencies like ruby2.0, gdebi, awscli, and also fetches the installer from `https://s3.amazonaws.com/aws-codedeploy-us-east-1/latest/install`.  

When we boot that base AMI, we run the installer and start the service.  This is where I get the error, until it eventually starts working.

Is it possible /etc/profile doesn't get sourced right at service start up?

**Comment by suryanarayanan** [comment]
The debug log you pasted has a clean run so it doesn't help me much. I would like to see the debug log for failed start ups.
The service sources /etc/profile once during startup. If there's any problem with it I wouldn't expect the agent to eventually work after two failed attempts.

**Comment by nwalke** [comment]
That appears to be exactly what's happening though.  Here's my log with verbose set to true on a "new" install: https://gist.github.com/nwalke/326e01ecfdb52a1de5dd

This server had never had CodeDeploy running or installed, so this should be as fresh as I can get.  

Unfortunately, I don't see any eye openers with verbose set to true in the config file `/etc/codedeploy-agent/conf/codedeployagent.yml`.

**Comment by Jason733i** [comment]
I'm experiencing a similar issue and have set verbose to true.
https://gist.github.com/Jason733i/e7468cadeae9bebf6275

I'm not exactly sure what's wrong with our setup, so any help would be appreciated.

**Comment by suryanarayanan** [comment]
@nwalke I don't see any debug logs. When you install the agent, by default the logging is non verbose. If you update the config you might have to restart the agent. 
I'm trying to figure out if this issue happens only during instance start up or during every agent install. Can you try not to install the agent during instance start up but manually install once the instance comes up and see if you see similar issue? Also if you are using cloud init, what are you doing in those scripts?

@Jason733i  based on the log line
"2015-09-29 17:43:13 DEBUG [codedeploy-agent(8506)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: #<Errno::ETIMEDOUT: Connection timed out - connect(2)>"
The agent is not able to hit the CodeDeploy service endpoint. Are you running the agent behind a proxy? If so have you set HTTP_PROXY with your proxy url in /etc/profile?

**Comment by Jason733i** [comment]
@suryanarayanan, it turned out we had our production routing tables out of whack.  I believe the routing table was incorrectly configured such that no outbound connections could be established. Thank you for the thoughtful reply!

**Comment by nwalke** [comment]
@suryanarayanan Got it fixed here: https://gist.github.com/nwalke/023f0f7404c89b0be4f4

We make an AMI that has the codedeploy agent installer downloaded to it, and then when we go to boot the AMI, we run the installer.

Before the installer runs, we set the file `/etc/profile.d/codedeployssl.sh` which sets the `AWS_SSL_CA_DIRECTORY` environment variable.

**Comment by nwalke** [comment]
The same instance minutes later: https://gist.github.com/nwalke/d2763c5844897471601e

I don't know what is different between the agent runs, but eventually the agent sees that the cert is valid (given our CA in `/etc/ssl/certs`).

**Comment by suryanarayanan** [comment]
@nwalke It looks like there's no problem with your certs. Please see
```
2015-10-01 10:45:32 ERROR [codedeploy-agent(4101)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: Error during certificate verification on codedeploy endpoint https://codedeploy-commands.us-east-1.amazonaws.com
2015-10-01 10:45:32 DEBUG [codedeploy-agent(4101)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: #Errno::ETIMEDOUT: Connection timed out - connect(2)
```
This shows that the agent isn't able to talk to CodeDeploy endpoint for some times after instance start up. As soon as it can connect to the endpoint, the cert verification kicks off, succeeds and eventually everything works fine. So it could be how and when you set up your routing tables and  other proxy related settings.

**Comment by nwalke** [comment]
@suryanarayanan You're absolutely right.  We had iptables rules generated by chef (runs every 15 minutes) and it wouldn't allow traffic for our new instances until the next chef run.  This caused the codedeploy agent to not be able to connect at first start up.  Wish I would have seen that sooner.

Thanks for helping me out with this!
