### ISSUE TITLE
Deployment failure CentOS 7.9

### ISSUE THREAD

**Issue by pankajsoni19** [aws/aws-codedeploy-agent#280]
I am deploying via bitbucket pipelines to s3 to code deploy to ec2.

1. The artifact a zip file gets copied correctly into S3. 
2. Deployment ID is generated in code deploy.

On centOS I am getting this error in code deploy log

```
2021-03-04 09:19:57 ERROR [codedeploy-agent(1470)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Error during perform: Aws::S3::Errors::PermanentRedirect - The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint. - /opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/seahorse/client/plugins/raise_response_errors.rb:17:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/plugins/sse_cpk.rb:24:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/plugins/dualstack.rb:30:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/plugins/accelerate.rb:47:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/aws-sdk-core/plugins/jsonvalue_converter.rb:22:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/aws-sdk-core/plugins/idempotency_token.rb:19:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/aws-sdk-core/plugins/param_converter.rb:26:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/seahorse/client/plugins/request_callback.rb:71:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/aws-sdk-core/plugins/response_paging.rb:12:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/seahorse/client/plugins/response_target.rb:24:in `call'
/opt/codedeploy-agent/vendor/gems/aws-sdk-core-3.109.0/lib/seahorse/client/request.rb:72:in `send_request'
/opt/codedeploy-agent/vendor/gems/aws-sdk-s3-1.81.0/lib/aws-sdk-s3/client.rb:5100:in `get_object'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:255:in `block in download_from_s3'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:249:in `open'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:249:in `download_from_s3'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:84:in `block in <class:CommandExecutor>'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:70:in `execute_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:115:in `process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:97:in `acknowledge_and_process_command'
/opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_poller.rb:76:in `block in perform'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `call'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/opt/codedeploy-agent/vendor/gems/concurrent-ruby-1.0.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
/opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
2021-03-04 09:19:57 WARN  [codedeploy-agent(1470)]: InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller: Calling PutHostCommandComplete: "Code Error" 
2021-03-04 09:19:57 INFO  [codedeploy-agent(1470)]: Version file found in /opt/codedeploy-agent/.version with agent version OFFICIAL_1.3.1-1880_rpm.
2021-03-04 09:19:57 INFO  [codedeploy-agent(1470)]: [Aws::CodeDeployCommand::Client 200 0.017981 0 retries] put_host_command_complete(command_status:"Failed",diagnostics:{format:"JSON",payload:"{\"error_code\":5,\"script_name\":\"\",\"message\":\"The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.\",\"log\":\"\"}"},host_command_identifier:".....")  

```

**Comment by pankajsoni19** [comment]
error in code deploy console

```
The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Comment by pankajsoni19** [comment]
console logs

```
INFO: Deploying app from revision.
aws deploy get-application-revision --application-name api-server --revision revisionType=S3,s3Location={bucket=png, bundleType=zip,key=deployments/api-server-preprod-d37c9a55e931636eaefefc1703356cbc0c1b6d36.zip}
aws deploy create-deployment --application-name api-server --deployment-group apis-staging --revision revisionType=S3,s3Location={bucket=png,bundleType=zip,key=deployments/api-server-preprod-d37c9a55e931636eaefefc1703356cbc0c1b6d36.zip} --ignore-application-stop-failures --file-exists-behavior OVERWRITE
INFO: Deployment created with id d-KGLYSHJG8.
INFO: Waiting for deployment to complete.
aws deploy wait deployment-successful --deployment-id d-KGLYSHJG8
ERROR: Deployment failed. Fetching deployment information...
aws deploy get-deployment --deployment-id d-KGLYSHJG8

```

**Comment by philstrong** [comment]
Sounds like you're using an S3 endpoint that's redirecting

maybe https://stackoverflow.com/questions/25027462/aws-s3-the-bucket-you-are-attempting-to-access-must-be-addressed-using-the-spec

**Comment by pankajsoni19** [comment]
I forgot to update. 

I was under the impression that S3 buckets are global. I think AWS changed that sometime.

After switching to a bucket created in same region as my code deploy, this was resolved.
