### ISSUE TITLE
Meta service not found

### ISSUE THREAD

**Issue by erashdan** [aws/aws-codedeploy-agent#281]
Hi

I installed code agent On-Premise server (not by AWS) 
After reading instructions and create an application and register VPS 

Deployment not working caused by timeout 
After checking code agent logs here's the issue (I guess)
```bash
2021-03-28 00:00:22 ERROR [codedeploy-agent(15787)]: booting child: error during start or run: RuntimeError - HTTP error from metadata service: Not Found, code 404 - /opt/codedeploy-agent/lib/instance_metadata.rb:111:in `block in http_request'
2021-03-28 00:00:22 ERROR [codedeploy-agent(15787)]: booting child: error during start or run: SystemExit - exit - /opt/codedeploy-agent/lib/instance_agent/runner/child.rb:90:in `exit'
```

Please help

**Comment by erashdan** [comment]
My mistake I created file `codedeploy.onpremises.yml` in the wrong location 
thanks
