### ISSUE TITLE
Source sequence is illegal/malformed utf-8

### ISSUE THREAD

**Issue by ravimartins** [aws/aws-codedeploy-agent#284]
Hello guys,

I'm getting the following error when I try to deploy to my EC2 Instances. I have others applications, with the same structure, that is working perfectly.

I got this on codedeploy-agent-log:

[Aws::CodeDeployCommand::Client 200 0.078138 0 retries] put_host_command_complete(command_status:"Failed",diagnostics:{format:"JSON",payload:"{\"error_code\":5,\"script_name\":\"\",\"message\":\"source sequence is illegal/malformed utf-8\",\"log\":\"\"}"}

Someone knows what is happening?

**Comment by janusz-mw** [comment]
I have the same issue. I'm using EC2 Windows machine. 

I suspect that the error is caused by some diacritics in the file names, but didn't confirm that yet.

**Comment by kedde** [comment]
I had a similar issue running an ec2 instance where I had the danish letter 'ø' in one of the filenames 



> /aws-codedeploy-agent/lib/instance_agent/plugins/codedeploy/install_instruction.rb:169:in `to_json': source sequence is illegal/malformed utf-8 (JSON::GeneratorError)
>         from D:/git/aws-codedeploy-agent/lib/instance_agent/plugins/codedeploy/install_instruction.rb:169:in `to_json'
>         from D:/git/aws-codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:45:in `block in install'
>         from D:/git/aws-codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:44:in `open'
>         from D:/git/aws-codedeploy-agent/lib/instance_agent/plugins/codedeploy/installer.rb:44:in `install'
>         from D:/git/aws-codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:144:in `block in <class:CommandExecutor>'
>         from D:/git/aws-codedeploy-agent/lib/instance_agent/plugins/codedeploy/command_executor.rb:72:in `execute_command'
>         from D:/git/aws-codedeploy-agent/lib/aws/codedeploy/local/deployer.rb:86:in `block in execute_events'
>         from D:/git/aws-codedeploy-agent/lib/aws/codedeploy/local/deployer.rb:85:in `each'
>         from D:/git/aws-codedeploy-agent/lib/aws/codedeploy/local/deployer.rb:85:in `execute_events'
>         from D:/git/aws-codedeploy-agent/bin/codedeploy-local:129:in `<main>'

        
        
I found that encoding was set to IBM437
        

>  irb
> irb(main):001:0> __ENCODING__
> => #<Encoding:IBM437>

To solve the problem I ticked this box 
![image](https://user-images.githubusercontent.com/398745/123052243-e90e8c80-d402-11eb-8806-437441722e6e.png)


>  irb
irb(main):001:0> __ENCODING__
=> #<Encoding:UTF-8>

Maybe a possible solution to this in the code could be to force utf-8 encoding?

**Comment by janusz-mw** [comment]
@kedde thanks. Checking this box solves the issue.

**Comment by MartinHeynAndersen** [comment]
We have the same issue when trying to deploy our server package. Multiple files in the package is containg dainsh chars and we are unable to rename these files. We are deploying to a Windows server 2016 instance.
The workaround with activating the  feature "BETA: Use unicode UTF-8 for world wide language support" does not seem like a viable solution for us.

**Comment by mwjones-aws** [comment]
What is your operating system level locale setting?

**Comment by MartinHeynAndersen** [comment]
Hi Mike

The local of the target EC2 operating system is English(United States):
***@***.***

I tried changing it to Danish but it did not seem to help.

/Martin

Fra: Mike Jones ***@***.***>
Sendt: 14. december 2022 23:26
Til: aws/aws-codedeploy-agent ***@***.***>
Cc: Martin Heyn Andersen ***@***.***>; Comment ***@***.***>
Emne: Re: [aws/aws-codedeploy-agent] Source sequence is illegal/malformed utf-8 (#284)

  Dette er en ekstern e-mail


What is your operating system level locale setting?

-

**Comment by t0shiii** [comment]
@MartinHeynAndersen we will work on reproducing this issue and get back to you.
