### ISSUE TITLE
Simulate on-premise with EC2 instances

### ISSUE THREAD

**Issue by dz902** [aws/aws-codedeploy-agent#287]
Hi,

I'm trying to simulate on-premise deployment on EC2 before working on the real deal.

I followed official guide but found that deployment always fail as if the instance is completely unresponsive. On the instance everything seems normal and logs shows no commands were polled.

Further investigation shows that `host identifier` is the ARN of the EC2 instance, which to me is suspicious as the agent should have no idea of the ARN of the instance.

I have `/etc/codedeploy-agent/conf/codedeploy.onpremises.yml` in correct place and correctly formed, even tried adding `:on_premises_config_file:` in `codedeployagent.yml` and restart agent.

It seems no matter what I do, the agent always sees this instance (running Centos) as an EC2 instance and refuse to use the name I use to register it to CodeDeploy. I kind of believe that this is the reason I could not deploy to the instance.

How does the agent determine whether it is on on-premise or EC2? Is there a way to simulate on-premise on EC2 instance?

Thanks!

**Comment by dz902** [comment]
I also tried disable metadata service seeing this in the code, but got errors:

```
2021-06-09 16:54:36 INFO  [codedeploy-agent(5107)]: master 5107: Spawned child 1/1
2021-06-09 16:54:36 DEBUG [codedeploy-agent(5111)]: Registering Plugins: ["codedeploy"].
2021-06-09 16:54:36 DEBUG [codedeploy-agent(5111)]: Loading plugin codedeploy from /opt/codedeploy-agent/lib/instance_agent/plugins/codedeploy/register_plugin
2021-06-09 16:54:36 DEBUG [codedeploy-agent(5111)]: Registered Plugins: #<Set: {InstanceAgent::Plugins::CodeDeployPlugin::CommandPoller}>.
2021-06-09 16:54:36 INFO  [codedeploy-agent(5111)]: IMDSv2 http request failed, falling back to IMDSv1.
2021-06-09 16:54:36 INFO  [codedeploy-agent(5111)]: IMDSv2 http request failed, falling back to IMDSv1.
2021-06-09 16:54:36 ERROR [codedeploy-agent(5111)]: booting child: error during start or run: RuntimeError - HTTP error from metadata service: Forbidden, code 403 - /opt/codedeploy-agent/lib/instance_metadata.rb:111:in `block in http_request'
/usr/share/ruby/net/http.rb:852:in `start'
/usr/share/ruby/net/http.rb:582:in `start'
/opt/codedeploy-agent/lib/instance_metadata.rb:104:in `http_request'
/opt/codedeploy-agent/lib/instance_metadata.rb:129:in `get_request'
/opt/codedeploy-agent/lib/instance_metadata.rb:98:in `rescue in get_instance_metadata'
```

It seems the `403` caused the agent to panic. This is strange, from the code it seems metadata is irrelevant if on-premise config is present. Also error code should not stop the agent from running as this indicates user is running the agent on-premises.

**Comment by dz902** [comment]
Here is my on-premise config file:

```
iam-session-arn: arn:aws-cn:sts::12345678:assumed-role/CodeDeployInstanceRole/test
aws_credentials_file: /etc/codedeploy-agent/conf/credentials
region: cn-northwest-1
```
```

**Comment by dz902** [comment]
Darn! I can't recall where I copied the config file, it messed `_` with `-`. Closing this.

I sincerely suggest if a on-premises file is read but none of the config is present, throw a warning or info log. Pulled my hair for hours.
