### ISSUE TITLE
SSL Error On-Premises Windows

### ISSUE THREAD

**Issue by dgreenbean** [aws/aws-codedeploy-agent#34]
I am getting the following SSL certificate error with an on-premises Windows machine:
```
2015-11-06 07:47:57 ERROR [codedeploy-agent(21272)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: Error during certificate verification on codedeploy endpoint https://codedeploy-commands.eu-west-1.amazonaws.com
2015-11-06 07:47:57 DEBUG [codedeploy-agent(21272)]: InstanceAgent::Plugins::CodeDeployPlugin::CodeDeployControl: #<OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed>
2015-11-06 07:47:57 ERROR [codedeploy-agent(21272)]: Error validating the SSL configuration: Invalid server certificate
2015-11-06 07:47:57 ERROR [codedeploy-agent(21272)]: CodeDeploy Instance Agent Service: CodeDeploy Instance Agent Service: error during start or run: SystemExit - Stopping CodeDeploy agent due to SSL validation error. - c:/temp/ocr7A98.tmp/src/lib/instance_agent/plugins/codedeploy/command_poller.rb:44:in `abort'
c:/temp/ocr7A98.tmp/src/lib/instance_agent/plugins/codedeploy/command_poller.rb:44:in `validate'
```

To install the CodeDeploy agent, I installed the AWS CLI, copied conf.onpremises.yml to C:\ProgramData\Amazon\CodeDeploy, downloaded codedeploy-agent.msi, and ran the MSI installation.

What am I missing?

**Comment by suryanarayanan** [comment]
Hi,
Can you tell us the codedeploy agent version you are running? You can look up this information using Windows service control manager.
Thanks.

**Comment by dgreenbean** [comment]
The CodeDeploy Agent version is v1.0.3.1.

**Comment by suryanarayanan** [comment]
v1.0.3.1 is a very old version. Could you please use the latest version.
The latest CodeDeploy agent can be downloaded from
https://s3-eu-west-1.amazonaws.com/aws-codedeploy-eu-west-1/latest/codedeploy-agent.msi
The version should say 1.0.1.825
Thanks.

**Comment by dgreenbean** [comment]
That seems to have worked.  Thanks!
