### ISSUE TITLE
Announcement: Releasing Agent 1.5.0 to all regions

### ISSUE THREAD

**Issue by mwjones-aws** [aws/aws-codedeploy-agent#349]
## Agent 1.5.0

[Installation Instructions](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent-operations-install.html)

[Release Notes](https://docs.aws.amazon.com/codedeploy/latest/userguide/codedeploy-agent.html#codedeploy-agent-version-history)

*1.5.x branch coming to Github soon*

#### MSI
 - latest/codedeploy-agent.msi
 - releases/codedeploy-agent-1.5.0.57.msi
 - ETag: "46e324841ab9a6fae5f4af1c956473fd"

#### DEB
 - latest/codedeploy-agent_all.deb
 - releases/codedeploy-agent_1.5.0-57_all.deb
 - ETag: "a5a0a7a6568b357fdad1f2806ba12308"

#### RPM
 - latest/codedeploy-agent.noarch.rpm
 - releases/codedeploy-agent-1.5.0-57.noarch.rpm
 - ETag: "edc76825fe23aa51c692b6e74f635f6a"

### Region availability

We estimate CodeDeploy Agent 1.5.0 will be available in all commercial regions by **2023-03-10**.

#### Available in these regions as of 2023-03-06
- ap-southeast-1
- eu-west-1
- us-east-1

**Comment by philstrong** [comment]
Yep, Ruby 3 support!

**Comment by herrsergio** [comment]
Installing the latest RPM version in Amazon Linux 2023 is not working:

```
# cat /etc/system-release && rpm -qa | grep -i codedeploy
Amazon Linux release 2023 (Amazon Linux)
codedeploy-agent-1.5.0-57.noarch
```

```
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require': cannot load such file -- net/smtp (LoadError)
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/appenders/email.rb:2:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/appenders.rb:57:in `<module:Logging>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging/appenders.rb:2:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging.rb:537:in `<module:Logging>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/logging-1.8.2/lib/logging.rb:18:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:160:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:149:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/log.rb:2:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:96:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:96:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager.rb:9:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:160:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:149:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/lib/instance_agent.rb:10:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:22:in `<main>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require': cannot load such file -- logging (LoadError)
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: Did you mean?  logger
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:148:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager/log.rb:2:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:96:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:96:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/vendor/gems/process_manager-0.0.13/lib/process_manager.rb:9:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:160:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:149:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/lib/instance_agent.rb:10:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:22:in `<main>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- process_manager (LoadError)
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/lib/instance_agent.rb:10:in `<top (required)>'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from <internal:/usr/share/ruby3.2-rubygems/rubygems/core_ext/kernel_require.rb>:85:in `require'
Mar  9 17:48:32 ip-10-80-103-68 bash[4517]: #011from /opt/codedeploy-agent/bin/../lib/codedeploy-agent.rb:22:in `<main>'
Mar  9 17:48:32 ip-10-80-103-68 systemd[1]: codedeploy-agent.service: Control process exited, code=exited, status=1/FAILURE
Mar  9 17:48:32 ip-10-80-103-68 systemd[1]: codedeploy-agent.service: Failed with result 'exit-code'.
```
